trainer:
  max_epochs: 10
  accelerator: gpu
  devices:
    - 0
root_dir: ${oc.env:PWD}
data:
  name: hdfs
  config:
    train_file: ${root_dir}/datasets/hdfs_datasets/train0.csv
    val_file: ${root_dir}/datasets/hdfs_datasets/val0.csv
    test_file: ${root_dir}/datasets/hdfs_datasets/test_normal.csv
    batch_size: 32
model:
  name: deeplog
  config:
    input_shape: 1
    mid_shape: 64
    n_classes: 33
    n_layers: 2
    lr: 0.01
